# Numpy 的属性介绍

In [37]:
import numpy as np

#### control + enter = run; command + enter = 下一个cell

In [7]:
#创建 numpy 的 ndarray对象
arr1 = np.arange(15).reshape(3,5)  #arange 生成0-14 一维数组
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
arr = np.arange(15,30).reshape(3,5)
print(arr)

[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [11]:
print(f'numpy的轴：{arr1.ndim}') #2
print(f'numpy的维度：{arr1.shape}') # （3，5） ， 3行5列
print(f'numpy的元素类型{arr1.dtype}') #int64
print(f'numpy的元素个数：{arr1.size}') # 15
print(f'numpy的元素占用字节数：{arr1.itemsize}')   # int 64%8 = 8

numpy的轴：2
numpy的维度：(3, 5)
numpy的元素类型int64
numpy的元素个数：15
numpy的元素占用字节数：8


## 创建Numpy的ndarray对象

- array()函数，把Python列表 变成 ndarray对象

In [22]:
# 创建Python列表对象
my_list = [11,22,33,44,55]
print(type(my_list))

#把python列表 变成 ndarray
arr2 = np.array(my_list)
print(arr2)
print(type(arr2))

<class 'list'>
[11 22 33 44 55]
<class 'numpy.ndarray'>


- arange()函数，创建ndarray对象

In [23]:
# arange(起始，结束，步长，dtype=类型)，类似于 Python中的range()函数。
# 1. 创建ndarray对象。
arr3 = np.arange(0, 10, 2, dtype=np.int32)   #相当于可以自定义
# 2. 打印ndarray对象。
print(arr3)
print(type(arr3))
print(f'numpy的元素类型{arr3.dtype}')

[0 2 4 6 8]
<class 'numpy.ndarray'>
numpy的元素类型int32


- 随机数生成ndarray对象

In [24]:
# random.rand() 生成 0.0~1.0 之间， 包左不包右的 随机小数矩阵
arr4 = np.random.rand(3,5)    #3行5列
print(arr4)
print(type(arr4))

[[0.460416   0.16779587 0.35782409 0.90382568 0.50139588]
 [0.27591606 0.42955643 0.00137587 0.15928287 0.52354765]
 [0.9115503  0.23069654 0.26950243 0.5479988  0.83812383]]
<class 'numpy.ndarray'>


In [25]:
# random.randint(起始值，结束值，size = (行，列）) 生成 指定范围， 包左不包右的 随机整数矩阵
arr5 = np.random.randint(3,9,size=(2,6))    #2行6列
print(arr5)
print(type(arr5))

[[8 4 6 5 7 7]
 [8 6 7 3 8 7]]
<class 'numpy.ndarray'>


In [26]:
# random.uniform(起始值，结束值，size = (行，列）) 生成 指定范围， 包左不包右的 随机小数矩阵
arr6 = np.random.uniform(3,9,size=(2,6))
print(arr6)
print(type(arr6))

[[7.06449484 5.86934735 7.19413815 5.8754153  5.59119139 7.67010088]
 [6.82249994 3.20613292 5.5000086  5.31678739 8.08695895 3.5791077 ]]
<class 'numpy.ndarray'>


## numpy的类型转换 astype()

In [5]:
# 创建ndarray对象
arr7 = np.arange(0,10,2,dtype=np.int64)
print(arr7)
print(arr7.dtype)

[0 2 4 6 8]
int64


In [6]:
arr8 = arr7.astype(np.float64)
print(arr8)
print(arr8.dtype)

[0. 2. 4. 6. 8.]
float64


## 创建等比数列

In [7]:
# 1. 创建等比数列。 参1：起始值（充当10的指数），参2：结束值（充当10的指数），参三：元素个数, 包左包右
arr9 = np.logspace(0,3,4)
print(arr9)
print(arr9.dtype)

[   1.   10.  100. 1000.]
float64


In [11]:
# 1. 创建等比数列。 参1：起始值（充当2的指数），参2：结束值（充当2的指数），参三：元素个数, 包左包右, 参四：修改底数为2,参五：修改数值类型
arr10 = np.logspace(0,3,4,base = 2,dtype=np.int64)
print(arr10)
print(arr10.dtype)

[1 2 4 8]
int64


## 创建等差数列

In [19]:
# 1. 创建等差数列
arr11 = np.linspace(1,10,4)
print(arr11)
print(arr11.dtype)

[ 1.  4.  7. 10.]
float64


In [18]:
# 1. 创建等差数列
arr11 = np.linspace(1,10,4,endpoint = False)
print(arr11)
print(arr11.dtype)

[1.   3.25 5.5  7.75]
float64


In [17]:
# 1. 创建等差数列参1：起始值，参2：结束值，参三：元素个数, 包左包右, 参四：是否包含结束值（包左不包右）,参五：修改数值类型
arr12 = np.linspace(1,10,4,endpoint = False,dtype=np.int64)
print(arr12)
print(arr12.dtype)

[1 3 5 7]
int64


# 基本函数

In [20]:
# 创建标准的正太分布序列
arr13 = np.random.randn(3,5)
print(arr13)

[[ 0.1463529   1.71640174 -0.11165324  1.30010199 -0.84587318]
 [ 0.76792998 -1.21538194  1.48033299  0.350021    1.16308931]
 [-0.14498808  0.86991655 -1.40497388 -0.45384377  0.43528227]]


In [21]:
# 测试基本函数
print(np.ceil(arr13))      # 天花板数 > 向上取整，比它大的，最小的那个整数

[[ 1.  2. -0.  2. -0.]
 [ 1. -1.  2.  1.  2.]
 [-0.  1. -1. -0.  1.]]


In [22]:
print(np.floor(arr13))

[[ 0.  1. -1.  1. -1.]
 [ 0. -2.  1.  0.  1.]
 [-1.  0. -2. -1.  0.]]


In [23]:
print(np.rint(arr13))   # 四舍五入

[[ 0.  2. -0.  1. -1.]
 [ 1. -1.  1.  0.  1.]
 [-0.  1. -1. -0.  0.]]


In [24]:
print(np.abs(arr13))

[[0.1463529  1.71640174 0.11165324 1.30010199 0.84587318]
 [0.76792998 1.21538194 1.48033299 0.350021   1.16308931]
 [0.14498808 0.86991655 1.40497388 0.45384377 0.43528227]]


In [27]:
print(np.multiply(arr13, arr13))   # 矩阵乘法（行列数一致）   相同位置的元素相乘
print(arr13 * arr13)

[[0.02141917 2.94603494 0.01246645 1.69026518 0.71550143]
 [0.58971645 1.47715325 2.19138575 0.1225147  1.35277674]
 [0.02102154 0.7567548  1.97395161 0.20597416 0.18947066]]
[[0.02141917 2.94603494 0.01246645 1.69026518 0.71550143]
 [0.58971645 1.47715325 2.19138575 0.1225147  1.35277674]
 [0.02102154 0.7567548  1.97395161 0.20597416 0.18947066]]


In [28]:
print(np.add(arr13, arr13))

[[ 0.29270581  3.43280348 -0.22330647  2.60020398 -1.69174636]
 [ 1.53585996 -2.43076387  2.96066597  0.70004199  2.32617862]
 [-0.28997615  1.7398331  -2.80994777 -0.90768753  0.87056454]]


In [29]:
print(np.divide(arr13, arr13))     # 矩阵除法（行列数一致）     相当于每个元素，自己除以自己

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
print(np.where(arr13 > 0, 1,-1))   # 如果元素大于0，则标记为1

[[ 1  1 -1  1 -1]
 [ 1 -1  1  1  1]
 [-1  1 -1 -1  1]]


# 统计函数

In [31]:
# 定义ndarray对象（数组对象）
arr14 = np.arange(12).reshape(3,4)
print(arr14)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
# 验证，累加和
print(np.cumsum(arr14))

66
[ 0  1  3  6 10 15 21 28 36 45 55 66]


In [34]:
# 求和
print(np.sum(arr14))
print(np.sum(arr14, axis = 0))   # 列
print(np.sum(arr14, axis = 1))   # 行

66
[12 15 18 21]
[ 6 22 38]


# 去重函数

In [38]:
# 定义函数
arr15 = np.array([[1,2,1],[2,3,5]])   # 2行3列
print(arr15)

[[1 2 1]
 [2 3 5]]


In [41]:
# 对上述元素去重
arr16 = np.unique(arr15)  #去重，返回新副本
print(arr15)
print(arr16)

[[1 2 1]
 [2 3 5]]
[1 2 3 5]


# 排序函数

In [42]:
# 通过 np.sort() 方式排序 > 返回新副本
arr17 = np.array([11,33,22,66,55])
print(arr17)
arr18 = np.sort(arr17)
print(arr18)

[11 33 22 66 55]
[11 22 33 55 66]


In [44]:
# 通过 数组对象.sort() > 直接修改原数组
arr17 = np.array([11,33,22,66,55])
print(arr17)
arr17.sort()
print(arr17)

[11 33 22 66 55]
[11 22 33 55 66]


# Numpy的矩阵运算

- 减法运算

In [47]:
# 定义数组
arr1 = np.array([10,20,30,40])
arr2 = np.array(4)
print(arr1)
print(arr2)
# 减法运算
print(arr1 - arr2)   #对应元素做减法运算
# 加法运算
print(arr1 + arr2)

[10 20 30 40]
4
[ 6 16 26 36]
[14 24 34 44]


- 矩阵乘法

In [48]:
# 1. 定义数组。
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1, 2, 3], [4, 5, 5]])
# 2. 打印数组
print(f'arr1: {arr1}')
print(f'arr2: {arr2}')

arr1: [[1 2 3]
 [4 5 6]]
arr2: [[1 2 3]
 [4 5 5]]


In [50]:
# 3. 矩阵乘法，行列数一致。
print(arr1 * arr2)  # 对应位置(坐标)的元素做乘法运算。

print(np.multiply(arr1, arr2))   # 效果同上

[[ 1  4  9]
 [16 25 30]]
[[ 1  4  9]
 [16 25 30]]


In [51]:
# 4. 矩阵乘法，行列数不一致。
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[9, 8], [6, 5], [3, 2]])
# 5. 打印数组。
print(f'arr3: {arr3}')
print(f'arr4: {arr4}')

arr3: [[1 2 3]
 [4 5 6]]
arr4: [[9 8]
 [6 5]
 [3 2]]


In [55]:
# 6. 矩阵乘法 → 行列数不一致。
# print(arr3 * arr4)    # 报错，行列数不一致。

print(arr3 @ arr4)       #语法糖      A：2行3列     B：3行2列      A列 = B行 即可操作    结果是：A行B列
print(np.dot(arr3, arr4))
print(arr3.dot(arr4))

[[30 24]
 [84 69]]
[[30 24]
 [84 69]]
[[30 24]
 [84 69]]


In [ ]:
# 7. A列 = B行即可操作，结果是：A行B列
arr3 = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])  # 2行4列
arr4 = np.array([[9, 8], [6, 5], [3, 2]])  # 3行2列
print(arr3 @ arr4)    # error