# Series对象入门

- 使用numpy创建series对象

        - Pandas中有两大核心对象，分别是：DataFrame和Series，其中，Series -> 一列数据，DataFrame -> 多列数据

#### 创建Series对象

In [1]:
import pandas as pd
import numpy as np

In [117]:
# 创建Series对象，采用：默认自增索引
s1 = pd.Series([1,2,3,4,5])
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [118]:
# 创建Series对象，采用：自定义索引
s2 = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
print(s2)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [119]:
# 使用字典，元组创建Series对象
# 元组形式
s3 = pd.Series((11,22,33,44,55))
print(s3)
# 字典形式
s4 = pd.Series({'a':1,'b':2,'c':3,'d':4})
print(s4)

0    11
1    22
2    33
3    44
4    55
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64


In [120]:
# 使用numpy > 创建Series对象
S5 = pd.Series(np.arange(5))
print(S5)

0    0
1    1
2    2
3    3
4    4
dtype: int64


# 2.2 Series 对象的属性

In [121]:
s6 = pd.Series(data=[0,1,2,3,4,5],index=['a','b','c','d','e','f'])
#print(s6)

# 加入列表推导式
s6 = pd.Series(data=[i for i in range(6)],index=[i for i in 'ABCDEF'])
print(s6)

A    0
B    1
C    2
D    3
E    4
F    5
dtype: int64


In [122]:
# 2. 获取Series对象的 索引列的值
print(s6.index)

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')


In [123]:
# 3. 获取Series对象的 值列的值
print(s6.values)

[0 1 2 3 4 5]


In [124]:
# Series支持根据 索引 获取元素， 即：Series 对象【索引值】
print(s6['D'])

3


In [125]:
# 根据索引， 修改Series对象的 元素值
s6['D'] = 99
print(s6)

A     0
B     1
C     2
D    99
E     4
F     5
dtype: int64


# DataFrame对象入门

         - · 每一列就是一个 Series（带有相同索引的一维数组）。
         - · 所有列共享同一个行索引（index），拼在一起就成了 DataFrame。

In [126]:
# 场景1 通过 字典 + 列表 的方式实现
# 准备数据集，每个键值对等于 一列数据
info = {
    'name': ['a','b','c','d'],
    'gender': ['male','female','male','female'],
    'age':[23,56,94,55]
}
# 把上述的数据集， 封装成DataFrame对象
df1 = pd.DataFrame(data = info)
print(df1)

  name  gender  age
0    a    male   23
1    b  female   56
2    c    male   94
3    d  female   55


In [127]:
# 场景1 通过 列表 + 元组 的方式实现
# 准备数据集，每个元组对等于 一行数据
info = [
    ('a','女',39),
    ('b','女',30),
    ('c','女',32),
]
# 把上述的数据集， 封装成DataFrame对象
df2 = pd.DataFrame(data = info)
print(df2)

   0  1   2
0  a  女  39
1  b  女  30
2  c  女  32


In [128]:
# 场景1 通过 列表 + 元组 的方式实现
# 准备数据集，每个元组对等于 一行数据
info = [
    ('a','女',39),
    ('b','女',30),
    ('c','女',32),
]
# 把上述的数据集， 封装成DataFrame对象
df2 = pd.DataFrame(data = info,columns=['name','gender','age'])
print(df2)

  name gender  age
0    a      女   39
1    b      女   30
2    c      女   32


In [129]:
# 场景1 通过 列表 + 列表 的方式实现
# 准备数据集，每个列表对等于 一行数据
info = [
    ['a','女',39],
    ['b','女',30],
    ['c','女',32],
]
# 把上述的数据集， 封装成DataFrame对象
df2 = pd.DataFrame(data = info,columns=['name','gender','age'])
print(df2)

  name gender  age
0    a      女   39
1    b      女   30
2    c      女   32


In [130]:
# 通过 numpy 的 ndarray 变成 pandas DataFrame 的方式实现
# 创建numpy 的 ndarray 对象
arr1 = np.arange(12).reshape(3,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [131]:
# 把上述的ndarray 对象，封装成DataFrame对象
df3 = pd.DataFrame(data = arr1,columns=['a','b','c','d'])
print(df3)

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


# 学生信息处理， DataFrame简单案例

In [132]:
# 生成10名同学，5门功课的成绩，成绩范围：40 ~ 100
score_df = pd.DataFrame(np.random.randint(40,101,(10,5)))      #测试一下，就知道包左不包右
print(score_df)

    0   1   2    3   4
0  60  90  42   53  72
1  86  85  99   95  67
2  90  82  73   91  63
3  96  71  49   71  87
4  83  40  86   61  92
5  90  68  60   44  47
6  88  82  75  100  62
7  58  75  52   72  93
8  98  70  88  100  71
9  97  51  53   79  87


In [133]:
# 修改DataFrame对象的 列名 和索引列值。
column_name  = ['语文','数学','英语','政治','体育']
index_name = ['同学' + str(i) for i in range(score_df.shape[0])]

# 具体修改DataFrame对象 列名 和 索引值的动作
# score_df.columns = column_name
# score_df.index = index_name

# rename 函数也可以
#score_df.rename(index ={0:'画画',1:'草草'}, columns= {0:'AI',1:"la"},inplace = True)
score_df.rename(index ={i:index_name[i] for i in range(score_df.shape[0])}, columns= {i: column_name[i] for i in range(score_df.shape[1])},inplace = True)

score_df

,语文,数学,英语,政治,体育
同学0,60,90,42,53,72
同学1,86,85,99,95,67
同学2,90,82,73,91,63
同学3,96,71,49,71,87
同学4,83,40,86,61,92
同学5,90,68,60,44,47
同学6,88,82,75,100,62
同学7,58,75,52,72,93
同学8,98,70,88,100,71
同学9,97,51,53,79,87


In [134]:
score_df.shape

(10, 5)

# DataFrame 的基本属性

In [135]:
# shape 维度， 即 行列数
print(score_df.shape)

(10, 5)


In [136]:
# index: 索引列
print(score_df.index)

Index(['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9'], dtype='object')


In [137]:
# columns 列名
print(score_df.columns)

Index(['语文', '数学', '英语', '政治', '体育'], dtype='object')


In [138]:
# data: 数据
print(score_df.values)

[[ 60  90  42  53  72]
 [ 86  85  99  95  67]
 [ 90  82  73  91  63]
 [ 96  71  49  71  87]
 [ 83  40  86  61  92]
 [ 90  68  60  44  47]
 [ 88  82  75 100  62]
 [ 58  75  52  72  93]
 [ 98  70  88 100  71]
 [ 97  51  53  79  87]]


In [139]:
# 行类转置
score_df.T

,同学0,同学1,同学2,同学3,同学4,同学5,同学6,同学7,同学8,同学9
语文,60,86,90,96,83,90,88,58,98,97
数学,90,85,82,71,40,68,82,75,70,51
英语,42,99,73,49,86,60,75,52,88,53
政治,53,95,91,71,61,44,100,72,100,79
体育,72,67,63,87,92,47,62,93,71,87


# DataFrame 的基本函数

In [140]:
#head(n), 查看前n行数据
score_df.head()  #默认5条

,语文,数学,英语,政治,体育
同学0,60,90,42,53,72
同学1,86,85,99,95,67
同学2,90,82,73,91,63
同学3,96,71,49,71,87
同学4,83,40,86,61,92


In [141]:
# tail(n) 查看后n行数据
score_df.tail() #默认5条

,语文,数学,英语,政治,体育
同学5,90,68,60,44,47
同学6,88,82,75,100,62
同学7,58,75,52,72,93
同学8,98,70,88,100,71
同学9,97,51,53,79,87


In [142]:
# info(), 查看df对象的详情信息
score_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 同学0 to 同学9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   语文      10 non-null     int64
 1   数学      10 non-null     int64
 2   英语      10 non-null     int64
 3   政治      10 non-null     int64
 4   体育      10 non-null     int64
dtypes: int64(5)
memory usage: 780.0+ bytes


In [143]:
# describe()查看df对象的 描述性 统计信息
score_df.describe()

,语文,数学,英语,政治,体育
count,10.000000,10.000000,10.000000,10.000000,10.000000
mean,84.600000,71.400000,67.700000,76.600000,74.100000
std,14.338759,15.579188,19.264533,19.895281,15.198319
min,58.000000,40.000000,42.000000,44.000000,47.000000
25%,83.750000,68.500000,52.250000,63.500000,64.000000
50%,89.000000,73.000000,66.500000,75.500000,71.500000
75%,94.500000,82.000000,83.250000,94.000000,87.000000
max,98.000000,90.000000,99.000000,100.000000,93.000000


In [144]:
# reset_index() 重置索引列
score_df.reset_index(drop=False) # drop = False, 默认值， 不删除原索引

,index,语文,数学,英语,政治,体育
0,同学0,60,90,42,53,72
1,同学1,86,85,99,95,67
2,同学2,90,82,73,91,63
3,同学3,96,71,49,71,87
4,同学4,83,40,86,61,92
5,同学5,90,68,60,44,47
6,同学6,88,82,75,100,62
7,同学7,58,75,52,72,93
8,同学8,98,70,88,100,71
9,同学9,97,51,53,79,87


In [145]:
score_df.reset_index(drop=True)

,语文,数学,英语,政治,体育
0,60,90,42,53,72
1,86,85,99,95,67
2,90,82,73,91,63
3,96,71,49,71,87
4,83,40,86,61,92
5,90,68,60,44,47
6,88,82,75,100,62
7,58,75,52,72,93
8,98,70,88,100,71
9,97,51,53,79,87


In [146]:
# set_index(): 重新设置索引
# score_df.set_index('语文')    #语文充当索引列

#语文，英语充当索引列
score_df.set_index(['语文','英语'])

,,数学,政治,体育
语文,英语,,,
60,42,90,53,72
86,99,85,95,67
90,73,82,91,63
96,49,71,71,87
83,86,40,61,92
90,60,68,44,47
88,75,82,100,62
58,52,75,72,93
98,88,70,100,71


# Pandas的数据类型介绍

In [147]:
# Pandas中的数据类型几乎和Python中是一致的，只不过有几个不太一样。
# 例如：Python: str → Pandas: object，Python: None → Pandas: nan, NAN, NaN,
# Pandas还支持category分类类型，针对于分类数据操作更快，更节省内存。

In [148]:
# 1. 创建DataFrame对象。
df = pd.DataFrame({
    'name': ['水冷哥', '深情哥', '紫琪', '德华'],
    'gender': ['女', '男', '保密', np.nan],
    'age': [81, 80, 66, 55]
})

df

,name,gender,age
0,水冷哥,女,81
1,深情哥,男,80
2,紫琪,保密,66
3,德华,NaN,55


In [149]:
# 3. 演示 日期类型 datetime
df2 = pd.DataFrame(['2025-03-29', '2025-03-30', '2025-03-31'], dtype='datetime64[ns]')   # ns是单位
print(df2)
print(df2.dtypes)

           0
0 2025-03-29
1 2025-03-30
2 2025-03-31
0    datetime64[ns]
dtype: object


# DataFrame建表需要注意的细节

In [150]:
'''
关键区别：

· 单层 []：列表里的每个元素都变成一行。
· 双层 [[]]：内层列表整体变成一行，内层列表里的每个元素变成一列。

在 pandas 的 DataFrame 里，元组和列表作为数据容器时，建出来的东西没有区别。
'''
import pandas as pd

# 情况1：双层括号 → 里面有3列 → 1行3列
df1 = pd.DataFrame([['A', 'B', 'C']])
print(df1)
#     0  1  2
# 0   A  B  C
print(df1.shape)  # (1, 3) → 1行3列


# 情况2：单层括号 → 只有1列 → 3行1列
df2 = pd.DataFrame(['A', 'B', 'C'])
print(df2)
#     0
# 0   A
# 1   B
# 2   C
print(df2.shape)  # (3, 1) → 3行1列

   0  1  2
0  A  B  C
(1, 3)
   0
0  A
1  B
2  C
(3, 1)


In [151]:
# 元组和列表效果一样
df1 = pd.DataFrame([('a', 'b', 'c')])  # 双层元组 → 1行3列
df2 = pd.DataFrame(['a', 'b', 'c'])    # 单层列表 → 3行1列
df3 = pd.DataFrame(('a', 'b', 'c'))    # 单层元组 → 3行1列
print(df1)
print('-' * 20)
print(df2)
print('-' * 20)
print(df3)

   0  1  2
0  a  b  c
--------------------
   0
0  a
1  b
2  c
--------------------
   0
0  a
1  b
2  c


In [152]:
# 字典 → 每个键值对是一列
df = pd.DataFrame({
    'name': ['A', 'B', 'C'],   # 这一列叫 name
    'age': [25, 30, 35]        # 这一列叫 age
})
# 结果：3行2列，有列名
print(df)

  name  age
0    A   25
1    B   30
2    C   35


# Pandas的数据类型介绍 继续

In [153]:
# 演示 日期差类型 timedelta
start_data = pd.to_datetime('2025-01-01')
end_data = pd.to_datetime('2025-12-31')
print(end_data - start_data)
print(type(end_data - start_data))

364 days 00:00:00
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>


In [154]:
# 5. 演示下 category 类型
s1 = pd.Series(['男', '女', '保密'], dtype='category')
print(s1)
print(type(s1))
print(s1.dtypes)  # category

0     男
1     女
2    保密
dtype: category
Categories (3, object): ['保密', '女', '男']
<class 'pandas.core.series.Series'>
category


# Pandas的基本操作

#### 加载数据

In [3]:
df = pd.read_csv('/Users/yiruihe/Desktop/python/machine_learningProject/stock_day.csv')
print(df)

             open   high  close    low     volume  price_change  p_change  \
2018-02-27  23.53  25.88  24.16  23.53   95578.03          0.63      2.68   
2018-02-26  22.80  23.78  23.53  22.80   60985.11          0.69      3.02   
2018-02-23  22.88  23.37  22.82  22.71   52914.01          0.54      2.42   
2018-02-22  22.25  22.76  22.28  22.02   36105.01          0.36      1.64   
2018-02-14  21.49  21.99  21.92  21.48   23331.04          0.44      2.05   
...           ...    ...    ...    ...        ...           ...       ...   
2015-03-06  13.17  14.48  14.28  13.13  179831.72          1.12      8.51   
2015-03-05  12.88  13.45  13.16  12.87   93180.39          0.26      2.02   
2015-03-04  12.80  12.92  12.90  12.61   67075.44          0.20      1.57   
2015-03-03  12.52  13.06  12.70  12.52  139071.61          0.18      1.44   
2015-03-02  12.25  12.67  12.52  12.20   96291.73          0.32      2.62   

               ma5    ma10    ma20      v_ma5     v_ma10     v_ma20  turnov

In [156]:
# 移除不需要的字段
# 2. 移除不需要的字段。
df.drop(columns=['ma5', 'ma10', 'ma20', 'v_ma5', 'v_ma10', 'v_ma20'], axis=0, inplace=True)  # 0: 列 (column) , 1: 行
df

,open,high,close,low,volume,price_change,p_change,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,2.39
2018-02-26,22.80,23.78,23.53,22.80,60985.11,0.69,3.02,1.53
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,1.32
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,0.90
2018-02-14,21.49,21.99,21.92,21.48,23331.04,0.44,2.05,0.58
...,...,...,...,...,...,...,...,...
2015-03-06,13.17,14.48,14.28,13.13,179831.72,1.12,8.51,6.16
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,3.19
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,2.30
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,4.76


In [157]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 643 entries, 2018-02-27 to 2015-03-02
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   open          643 non-null    float64
 1   high          643 non-null    float64
 2   close         643 non-null    float64
 3   low           643 non-null    float64
 4   volume        643 non-null    float64
 5   price_change  643 non-null    float64
 6   p_change      643 non-null    float64
 7   turnover      643 non-null    float64
dtypes: float64(8)
memory usage: 45.2+ KB


In [158]:
df.describe()

,open,high,close,low,volume,price_change,p_change,turnover
count,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000
mean,21.272706,21.900513,21.336267,20.771835,99905.519114,0.018802,0.190280,2.936190
std,3.930973,4.077578,3.942806,3.791968,73879.119354,0.898476,4.079698,2.079375
min,12.250000,12.670000,12.360000,12.200000,1158.120000,-3.520000,-10.030000,0.040000
25%,19.000000,19.500000,19.045000,18.525000,48533.210000,-0.390000,-1.850000,1.360000
50%,21.440000,21.970000,21.450000,20.980000,83175.930000,0.050000,0.260000,2.500000
75%,23.400000,24.065000,23.415000,22.850000,127580.055000,0.455000,2.305000,3.915000
max,34.990000,36.350000,35.210000,34.010000,501915.410000,3.030000,10.030000,12.560000


#### 索引操作

In [159]:
# 根据行列索引获取元素， 先列后行
df['open']['2018-02-27']

np.float64(23.53)

In [160]:
# 结合 loc 根据： 行索引 和列名 来获取元素
# df.loc[行索引，列名]
# df.iloc[行索引，列索引]
df.loc['2018-02-27','high'] # 获取一条数据
df.loc['2018-02-27':'2018-02-14',['open','high']]   #注意提取的数值位置必须按表格上来，与日期本身的排序无关

,open,high
2018-02-27,23.53,25.88
2018-02-26,22.80,23.78
2018-02-23,22.88,23.37
2018-02-22,22.25,22.76
2018-02-14,21.49,21.99


In [161]:
# 结合 iloc 根据： 行索引 和 列索引 来获取元素 (包左不不包右）
df.iloc[0:5,0:2]

,open,high
2018-02-27,23.53,25.88
2018-02-26,22.80,23.78
2018-02-23,22.88,23.37
2018-02-22,22.25,22.76
2018-02-14,21.49,21.99


In [162]:
df

,open,high,close,low,volume,price_change,p_change,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,2.39
2018-02-26,22.80,23.78,23.53,22.80,60985.11,0.69,3.02,1.53
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,1.32
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,0.90
2018-02-14,21.49,21.99,21.92,21.48,23331.04,0.44,2.05,0.58
...,...,...,...,...,...,...,...,...
2015-03-06,13.17,14.48,14.28,13.13,179831.72,1.12,8.51,6.16
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,3.19
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,2.30
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,4.76


In [165]:
# 赋值操作
df['open'] = 23
df.low = 1   # 效果同上，更简单，但有弊端：字段名含空格或特殊字符时无法使用，例如 df.max_value 必须写成 df['max_value']
df

,open,high,close,low,volume,price_change,p_change,turnover
2018-02-27,23,25.88,24.16,1,95578.03,0.63,2.68,2.39
2018-02-26,23,23.78,23.53,1,60985.11,0.69,3.02,1.53
2018-02-23,23,23.37,22.82,1,52914.01,0.54,2.42,1.32
2018-02-22,23,22.76,22.28,1,36105.01,0.36,1.64,0.90
2018-02-14,23,21.99,21.92,1,23331.04,0.44,2.05,0.58
...,...,...,...,...,...,...,...,...
2015-03-06,23,14.48,14.28,1,179831.72,1.12,8.51,6.16
2015-03-05,23,13.45,13.16,1,93180.39,0.26,2.02,3.19
2015-03-04,23,12.92,12.90,1,67075.44,0.20,1.57,2.30
2015-03-03,23,13.06,12.70,1,139071.61,0.18,1.44,4.76


In [169]:
# 切换成原数据
df = pd.read_csv('/Users/yiruihe/Desktop/python/machine_learningProject/stock_day.csv')
df

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-02-26,22.80,23.78,23.53,22.80,60985.11,0.69,3.02,22.406,21.955,22.942,40827.52,42736.34,56007.50,1.53
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,21.938,21.929,23.022,35119.58,41871.97,56372.85,1.32
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,21.446,21.909,23.137,35397.58,39904.78,60149.60,0.90
2018-02-14,21.49,21.99,21.92,21.48,23331.04,0.44,2.05,21.366,21.923,23.253,33590.21,42935.74,61716.11,0.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-03-06,13.17,14.48,14.28,13.13,179831.72,1.12,8.51,13.112,13.112,13.112,115090.18,115090.18,115090.18,6.16
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,12.820,12.820,12.820,98904.79,98904.79,98904.79,3.19
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,12.707,12.707,12.707,100812.93,100812.93,100812.93,2.30
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,12.610,12.610,12.610,117681.67,117681.67,117681.67,4.76


In [171]:
# 基于开盘价格 升序 做排序
df.sort_values(by = 'open', ascending = True) # 升序
df.sort_values(by = 'open', ascending = False)   # 降序

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2015-06-15,34.99,34.99,31.69,31.69,199369.53,-3.52,-10.00,33.696,30.964,29.114,201148.55,164608.26,158362.17,6.82
2015-06-12,34.69,35.98,35.21,34.01,159825.88,0.82,2.38,33.420,30.513,28.683,197248.25,154480.41,153888.00,5.47
2015-06-10,34.10,36.35,33.85,32.23,269033.12,0.51,1.53,30.538,28.660,27.424,176305.53,152266.76,149078.50,9.21
2017-11-01,33.85,34.34,33.83,33.10,232325.30,-0.61,-1.77,33.170,30.891,28.684,353499.64,346829.10,233701.92,5.81
2015-06-11,33.17,34.98,34.39,32.51,173075.73,0.54,1.59,32.016,29.572,28.036,193141.45,151337.71,151428.57,5.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,12.820,12.820,12.820,98904.79,98904.79,98904.79,3.19
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,12.707,12.707,12.707,100812.93,100812.93,100812.93,2.30
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,12.610,12.610,12.610,117681.67,117681.67,117681.67,4.76
2015-09-02,12.30,14.11,12.36,12.30,70201.74,-1.10,-8.17,14.440,16.591,18.360,96977.99,98537.72,104567.25,2.40


In [172]:
# 基于开盘价格降序排列， 价格一样， 基于 当日最高价格（high） 降序排列
df.sort_values(by = ['open','high'], ascending = [False,False])

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2015-06-15,34.99,34.99,31.69,31.69,199369.53,-3.52,-10.00,33.696,30.964,29.114,201148.55,164608.26,158362.17,6.82
2015-06-12,34.69,35.98,35.21,34.01,159825.88,0.82,2.38,33.420,30.513,28.683,197248.25,154480.41,153888.00,5.47
2015-06-10,34.10,36.35,33.85,32.23,269033.12,0.51,1.53,30.538,28.660,27.424,176305.53,152266.76,149078.50,9.21
2017-11-01,33.85,34.34,33.83,33.10,232325.30,-0.61,-1.77,33.170,30.891,28.684,353499.64,346829.10,233701.92,5.81
2015-06-11,33.17,34.98,34.39,32.51,173075.73,0.54,1.59,32.016,29.572,28.036,193141.45,151337.71,151428.57,5.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,12.820,12.820,12.820,98904.79,98904.79,98904.79,3.19
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,12.707,12.707,12.707,100812.93,100812.93,100812.93,2.30
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,12.610,12.610,12.610,117681.67,117681.67,117681.67,4.76
2015-09-02,12.30,14.11,12.36,12.30,70201.74,-1.10,-8.17,14.440,16.591,18.360,96977.99,98537.72,104567.25,2.40


In [173]:
# 按照索引排序
df.sort_index(ascending = True)   # 默认升序

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2015-03-02,12.25,12.67,12.52,12.20,96291.73,0.32,2.62,12.520,12.520,12.520,96291.73,96291.73,96291.73,3.30
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,12.610,12.610,12.610,117681.67,117681.67,117681.67,4.76
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,12.707,12.707,12.707,100812.93,100812.93,100812.93,2.30
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,12.820,12.820,12.820,98904.79,98904.79,98904.79,3.19
2015-03-06,13.17,14.48,14.28,13.13,179831.72,1.12,8.51,13.112,13.112,13.112,115090.18,115090.18,115090.18,6.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-02-14,21.49,21.99,21.92,21.48,23331.04,0.44,2.05,21.366,21.923,23.253,33590.21,42935.74,61716.11,0.58
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,21.446,21.909,23.137,35397.58,39904.78,60149.60,0.90
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,21.938,21.929,23.022,35119.58,41871.97,56372.85,1.32
2018-02-26,22.80,23.78,23.53,22.80,60985.11,0.69,3.02,22.406,21.955,22.942,40827.52,42736.34,56007.50,1.53


In [175]:
# 演示 Series 对象也有 sort_index() ， sort_values() 排序方法
df.open.sort_index(ascending = True)   #索引升序
df.open.sort_values(ascending = False)  #价格降序

2015-06-15    34.99
2015-06-12    34.69
2015-06-10    34.10
2017-11-01    33.85
2015-06-11    33.17
              ...  
2015-03-05    12.88
2015-03-04    12.80
2015-03-03    12.52
2015-09-02    12.30
2015-03-02    12.25
Name: open, Length: 643, dtype: float64

# DataFrame 的运算

#### 算数运算

In [4]:
df

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-02-26,22.80,23.78,23.53,22.80,60985.11,0.69,3.02,22.406,21.955,22.942,40827.52,42736.34,56007.50,1.53
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,21.938,21.929,23.022,35119.58,41871.97,56372.85,1.32
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,21.446,21.909,23.137,35397.58,39904.78,60149.60,0.90
2018-02-14,21.49,21.99,21.92,21.48,23331.04,0.44,2.05,21.366,21.923,23.253,33590.21,42935.74,61716.11,0.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-03-06,13.17,14.48,14.28,13.13,179831.72,1.12,8.51,13.112,13.112,13.112,115090.18,115090.18,115090.18,6.16
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,12.820,12.820,12.820,98904.79,98904.79,98904.79,3.19
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,12.707,12.707,12.707,100812.93,100812.93,100812.93,2.30
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,12.610,12.610,12.610,117681.67,117681.67,117681.67,4.76


In [5]:
# 针对于 close 列值 + 2 处理
df.close + 2  # Series对象 和 数值运算， 则Series 中的每一个数值都会和该数字进行运算
df.close.add(2) # 效果同上

2018-02-27    26.16
2018-02-26    25.53
2018-02-23    24.82
2018-02-22    24.28
2018-02-14    23.92
              ...  
2015-03-06    16.28
2015-03-05    15.16
2015-03-04    14.90
2015-03-03    14.70
2015-03-02    14.52
Name: close, Length: 643, dtype: float64

In [6]:
# 3. 针对于 low列的值 - 10 处理
# df.low.sub(10)
df.low - 10    # 效果同上

2018-02-27    13.53
2018-02-26    12.80
2018-02-23    12.71
2018-02-22    12.02
2018-02-14    11.48
              ...  
2015-03-06     3.13
2015-03-05     2.87
2015-03-04     2.61
2015-03-03     2.52
2015-03-02     2.20
Name: low, Length: 643, dtype: float64

# 逻辑运算符

In [7]:
# 筛选出 open列值 > 23的数据
df.open > 23   # 这个是大于23 true ,反之 false 不是赛选

2018-02-27     True
2018-02-26    False
2018-02-23    False
2018-02-22    False
2018-02-14    False
              ...  
2015-03-06    False
2015-03-05    False
2015-03-04    False
2015-03-03    False
2015-03-02    False
Name: open, Length: 643, dtype: bool

In [8]:
df[df.open > 23]

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-02-01,23.71,23.86,22.42,22.22,66414.64,-1.30,-5.48,23.646,24.365,24.279,52812.35,80394.43,88480.92,1.66
2018-01-31,23.85,23.98,23.72,23.31,49155.02,-0.11,-0.46,24.036,24.583,24.411,60348.94,80496.48,91666.75,1.23
2018-01-30,23.71,24.08,23.83,23.70,32420.43,0.05,0.21,24.350,24.671,24.365,77485.53,84805.23,92943.35,0.81
2018-01-29,24.40,24.63,23.77,23.72,65469.81,-0.73,-2.98,24.684,24.728,24.294,91842.60,91692.73,93456.22,1.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-05-21,27.50,28.22,28.22,26.50,121190.11,2.57,10.02,24.508,22.725,22.053,117760.48,103865.87,98766.20,4.15
2015-05-20,24.10,25.65,25.65,24.10,164143.16,2.33,9.99,23.292,21.784,21.733,118737.32,98652.00,99743.64,5.62
2015-05-19,23.68,23.69,23.32,22.47,82945.73,0.25,1.08,22.318,21.166,21.536,100396.01,90830.02,97087.92,2.84
2015-04-16,24.63,25.21,22.97,21.94,221070.31,-1.41,-5.78,22.230,19.983,17.825,182172.04,153247.63,124317.19,7.57


In [11]:
# 赛选出 open列值 > 23, 且 < 24 的数据
df[(df.open > 23) & (df.open < 24)]
# 标准写法
df[(df['open'] > 23) & (df['open']< 24)]

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-02-01,23.71,23.86,22.42,22.22,66414.64,-1.30,-5.48,23.646,24.365,24.279,52812.35,80394.43,88480.92,1.66
2018-01-31,23.85,23.98,23.72,23.31,49155.02,-0.11,-0.46,24.036,24.583,24.411,60348.94,80496.48,91666.75,1.23
2018-01-30,23.71,24.08,23.83,23.70,32420.43,0.05,0.21,24.350,24.671,24.365,77485.53,84805.23,92943.35,0.81
2018-01-16,23.40,24.60,24.40,23.30,101295.42,0.96,4.10,23.908,24.058,23.321,82003.73,101081.47,74590.92,2.54
2018-01-12,23.70,25.15,24.24,23.42,120303.53,0.56,2.37,24.076,23.748,23.236,86133.33,91838.46,69690.35,3.01
2018-01-11,23.67,23.85,23.67,23.21,48525.75,-0.12,-0.50,24.130,23.548,23.197,102925.87,85432.61,65928.23,1.21
2017-12-22,23.21,23.39,22.99,22.90,28394.00,-0.21,-0.91,23.224,23.313,23.316,35689.43,50210.29,53887.77,0.71
2017-12-21,23.39,23.50,23.21,22.86,34005.55,-0.11,-0.47,23.226,23.275,23.389,38699.06,52743.10,55126.09,0.85
2017-12-20,23.61,23.96,23.33,23.20,43368.92,-0.14,-0.60,23.278,23.180,23.430,40910.18,54204.51,57245.14,1.09


In [10]:
# 可以通过 query()函数， 优化上述代码
df.query('open > 23 & open < 24')

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-02-01,23.71,23.86,22.42,22.22,66414.64,-1.30,-5.48,23.646,24.365,24.279,52812.35,80394.43,88480.92,1.66
2018-01-31,23.85,23.98,23.72,23.31,49155.02,-0.11,-0.46,24.036,24.583,24.411,60348.94,80496.48,91666.75,1.23
2018-01-30,23.71,24.08,23.83,23.70,32420.43,0.05,0.21,24.350,24.671,24.365,77485.53,84805.23,92943.35,0.81
2018-01-16,23.40,24.60,24.40,23.30,101295.42,0.96,4.10,23.908,24.058,23.321,82003.73,101081.47,74590.92,2.54
2018-01-12,23.70,25.15,24.24,23.42,120303.53,0.56,2.37,24.076,23.748,23.236,86133.33,91838.46,69690.35,3.01
2018-01-11,23.67,23.85,23.67,23.21,48525.75,-0.12,-0.50,24.130,23.548,23.197,102925.87,85432.61,65928.23,1.21
2017-12-22,23.21,23.39,22.99,22.90,28394.00,-0.21,-0.91,23.224,23.313,23.316,35689.43,50210.29,53887.77,0.71
2017-12-21,23.39,23.50,23.21,22.86,34005.55,-0.11,-0.47,23.226,23.275,23.389,38699.06,52743.10,55126.09,0.85
2017-12-20,23.61,23.96,23.33,23.20,43368.92,-0.14,-0.60,23.278,23.180,23.430,40910.18,54204.51,57245.14,1.09


In [12]:
# 固定值的筛选， isin
# 查询open价格为 23.53， 23.67价格数据
df[(df.open == 23.53)|(df.open == 23.67)]

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-01-11,23.67,23.85,23.67,23.21,48525.75,-0.12,-0.50,24.130,23.548,23.197,102925.87,85432.61,65928.23,1.21
2017-07-26,23.53,23.92,23.40,22.85,110276.48,-0.30,-1.27,23.200,22.718,22.286,130237.86,140918.73,160464.67,2.76
2015-12-18,23.53,24.66,23.99,23.43,109230.05,0.65,2.79,22.834,22.264,22.163,66728.10,68518.08,68161.18,3.74


In [13]:
df.query('open == 23.53|open == 23.67')

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-01-11,23.67,23.85,23.67,23.21,48525.75,-0.12,-0.50,24.130,23.548,23.197,102925.87,85432.61,65928.23,1.21
2017-07-26,23.53,23.92,23.40,22.85,110276.48,-0.30,-1.27,23.200,22.718,22.286,130237.86,140918.73,160464.67,2.76
2015-12-18,23.53,24.66,23.99,23.43,109230.05,0.65,2.79,22.834,22.264,22.163,66728.10,68518.08,68161.18,3.74


In [14]:
df[df.open.isin([23.53,23.67])]

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-01-11,23.67,23.85,23.67,23.21,48525.75,-0.12,-0.50,24.130,23.548,23.197,102925.87,85432.61,65928.23,1.21
2017-07-26,23.53,23.92,23.40,22.85,110276.48,-0.30,-1.27,23.200,22.718,22.286,130237.86,140918.73,160464.67,2.76
2015-12-18,23.53,24.66,23.99,23.43,109230.05,0.65,2.79,22.834,22.264,22.163,66728.10,68518.08,68161.18,3.74


In [15]:
df.query('open in [23.53,23.67]')

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-01-11,23.67,23.85,23.67,23.21,48525.75,-0.12,-0.50,24.130,23.548,23.197,102925.87,85432.61,65928.23,1.21
2017-07-26,23.53,23.92,23.40,22.85,110276.48,-0.30,-1.27,23.200,22.718,22.286,130237.86,140918.73,160464.67,2.76
2015-12-18,23.53,24.66,23.99,23.43,109230.05,0.65,2.79,22.834,22.264,22.163,66728.10,68518.08,68161.18,3.74


# 统计函数

In [16]:
df

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-02-26,22.80,23.78,23.53,22.80,60985.11,0.69,3.02,22.406,21.955,22.942,40827.52,42736.34,56007.50,1.53
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,21.938,21.929,23.022,35119.58,41871.97,56372.85,1.32
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,21.446,21.909,23.137,35397.58,39904.78,60149.60,0.90
2018-02-14,21.49,21.99,21.92,21.48,23331.04,0.44,2.05,21.366,21.923,23.253,33590.21,42935.74,61716.11,0.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-03-06,13.17,14.48,14.28,13.13,179831.72,1.12,8.51,13.112,13.112,13.112,115090.18,115090.18,115090.18,6.16
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,12.820,12.820,12.820,98904.79,98904.79,98904.79,3.19
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,12.707,12.707,12.707,100812.93,100812.93,100812.93,2.30
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,12.610,12.610,12.610,117681.67,117681.67,117681.67,4.76


In [17]:
df.describe()

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
count,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000,643.000000
mean,21.272706,21.900513,21.336267,20.771835,99905.519114,0.018802,0.190280,21.302362,21.267656,21.200946,100008.642691,100287.542177,100797.518398,2.936190
std,3.930973,4.077578,3.942806,3.791968,73879.119354,0.898476,4.079698,3.880640,3.813602,3.686186,62761.578326,56759.082060,50101.575639,2.079375
min,12.250000,12.670000,12.360000,12.200000,1158.120000,-3.520000,-10.030000,12.520000,12.520000,12.520000,10804.740000,19130.510000,23311.000000,0.040000
25%,19.000000,19.500000,19.045000,18.525000,48533.210000,-0.390000,-1.850000,18.990000,19.102000,19.275000,55794.985000,59861.955000,64103.675000,1.360000
50%,21.440000,21.970000,21.450000,20.980000,83175.930000,0.050000,0.260000,21.504000,21.623000,21.530000,86133.330000,89234.970000,96291.730000,2.500000
75%,23.400000,24.065000,23.415000,22.850000,127580.055000,0.455000,2.305000,23.318000,23.098500,23.136000,127655.655000,124693.255000,124001.015000,3.915000
max,34.990000,36.350000,35.210000,34.010000,501915.410000,3.030000,10.030000,33.696000,32.186000,29.998000,404443.540000,360028.160000,269280.790000,12.560000


In [21]:
# 统计函数 count(), mean(), median(), min(), max(), std(), var(), sum()
df.sum() # 针对于 每列（DataFrame对象） 进行求和
df.high.sum()  #针对于 high列 （Series对象） 进行求和
df.mean()      # 针对于每列(DataFrame对象)进行求平均值
df.median()    # 针对于每列(DataFrame对象)进行求中位数
df.cumsum()     # 针对于 每列（DataFrame对象）进行求累计求和

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
2018-02-27,23.53,25.88,24.16,23.53,95578.03,0.63,2.68,22.942,22.142,22.875,53782.64,46738.65,55576.11,2.39
2018-02-26,46.33,49.66,47.69,46.33,156563.14,1.32,5.70,45.348,44.097,45.817,94610.16,89474.99,111583.61,3.92
2018-02-23,69.21,73.03,70.51,69.04,209477.15,1.86,8.12,67.286,66.026,68.839,129729.74,131346.96,167956.46,5.24
2018-02-22,91.46,95.79,92.79,91.06,245582.16,2.22,9.76,88.732,87.935,91.976,165127.32,171251.74,228106.06,6.14
2018-02-14,112.95,117.78,114.71,112.54,268913.20,2.66,11.81,110.098,109.858,115.229,198717.53,214187.48,289822.17,6.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-03-06,13627.90,14029.93,13667.94,13306.09,63843629.62,11.13,114.70,13646.762,13624.446,13581.551,63891866.13,64071198.50,64399113.21,1874.42
2015-03-05,13640.78,14043.38,13681.10,13318.96,63936810.01,11.39,116.72,13659.582,13637.266,13594.371,63990770.92,64170103.29,64498018.00,1877.61
2015-03-04,13653.58,14056.30,13694.00,13331.57,64003885.45,11.59,118.29,13672.289,13649.973,13607.078,64091583.85,64270916.22,64598830.93,1879.91
2015-03-03,13666.10,14069.36,13706.70,13344.09,64142957.06,11.77,119.73,13684.899,13662.583,13619.688,64209265.52,64388597.89,64716512.60,1884.67


#### apply()函数 -> 它可以执行自定义函数

In [ ]:
# 背景：目前我们用的都是Pandas提供好的函数，例如：count(), max(), min() ...
# 如果要传入一些自定义的逻辑，此时就需要用到 apply()函数了
# 格式：df.apply(自定义函数, axis=0)  # 0 → 列, 1 → 行

In [28]:
# 需求：同时获取到多列的最大值和最小值的差值。例如：open列，close列
df.open.max() - df.open.min()
df.close.max() - df.close.min()
# 1. 自定义函数 my_func，接收某列的数据，计算该列的最大值和最小值，返回差值。
def my_func(col):
    return col.max() - col.min()

# 2. 获取到 open列 和 close 列
df[['open','close']]
df.loc[:,['open','close']]
df.iloc[:,[0,2]]
df.iloc[:,0:3:2]

# 3. 通过apply()函数，调用上述的自定义函数，作用到指定的列。
df[['open','close']].apply(my_func)    # 把df的各个列分别传入函数，计算结果

open     22.74
close    22.85
dtype: float64

In [29]:
df[['open','close']].apply(my_func,axis = 1) # axis = 1 表示 对 行 进行操作

2018-02-27    0.63
2018-02-26    0.73
2018-02-23    0.06
2018-02-22    0.03
2018-02-14    0.43
              ... 
2015-03-06    1.11
2015-03-05    0.28
2015-03-04    0.10
2015-03-03    0.18
2015-03-02    0.27
Length: 643, dtype: float64

In [30]:
df[['open','close']].apply(my_func,axis = 0) # axis = 0 表示 对 列 进行操作  默认是0

open     22.74
close    22.85
dtype: float64

In [31]:
# 思路2：合并版，通过 lambda函数实现
df[['open','close']].apply(lambda col:col.max()-col.min())

open     22.74
close    22.85
dtype: float64